/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Rutina;

import Controlador.CRUD;
import Modelo.Ejercicio;
import Modelo.Rutina;
import Vista.Ejercicio.Crear_ejercicio;
import java.awt.Image;
import java.util.ArrayList;

import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alvaro Romo Villarreal
 */
public class Crear_rutina extends javax.swing.JFrame {

    private CRUD crud;
    private List<Ejercicio> listaEjercicios;
    private DefaultTableModel dtm;
//    Lista que se añade a la BBDD
    private ArrayList<Ejercicio> lst_ejercicios_añadir_BBDD;

    public Crear_rutina(CRUD crud) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        listaEjercicios = new ArrayList<>();

        this.crud = crud;
        dtm = (DefaultTableModel) tb_ejerccicios.getModel();
        lst_ejercicios_añadir_BBDD = new ArrayList<>();
        cargar_cb();
    }

    /**
     * Creates new form Crear_rutina
     */
    public Crear_rutina() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        listaEjercicios = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txf_nombre_rutina = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_descripcion = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_ejerccicios = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cb_ejercicios = new javax.swing.JComboBox<>();
        btn_eliminar = new javax.swing.JButton();
        btn_crear_rutina = new javax.swing.JButton();
        btn_aniadir_ejercicio = new javax.swing.JButton();
        lbl_imagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Nombre:");
        jLabel1.setMaximumSize(new java.awt.Dimension(41, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(41, 30));

        txf_nombre_rutina.setText("Pa sorprender al musculo");

        jLabel2.setText("Descripción:");
        jLabel2.setMaximumSize(new java.awt.Dimension(48, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(48, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(48, 16));

        txa_descripcion.setColumns(20);
        txa_descripcion.setRows(5);
        jScrollPane1.setViewportView(txa_descripcion);
        txa_descripcion.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(txf_nombre_rutina))
                .addGap(8, 8, 8))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_nombre_rutina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tb_ejerccicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "descripcion", "Descanso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_ejerccicios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_ejerccicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_ejercciciosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_ejerccicios);

        jLabel3.setText("Añadir Ejercicio:");

        cb_ejercicios.setToolTipText("Selecciona los ejercicios de tu rutina");

        btn_eliminar.setText("Eliminar Ejercicio");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_crear_rutina.setText("Crear Rutina");
        btn_crear_rutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crear_rutinaActionPerformed(evt);
            }
        });

        btn_aniadir_ejercicio.setText("Añadir Ejercicio ");
        btn_aniadir_ejercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aniadir_ejercicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_crear_rutina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_ejercicios, 0, 487, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_aniadir_ejercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cb_ejercicios, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_aniadir_ejercicio, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                    .addComponent(lbl_imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_crear_rutina, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Ejercicio");

        jMenuItem1.setText("Crear Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crear_rutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crear_rutinaActionPerformed
        // TODO add your handling code here:
        Rutina r = new Rutina();
        if (txf_nombre_rutina.getText().trim().isEmpty() || txa_descripcion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inserte al menos un nombre y una descripción para la rutina antes de crearla");
            return;
        }
        if (lst_ejercicios_añadir_BBDD.size() <= 0) {
            JOptionPane.showMessageDialog(this, "Seleccione al menos un ejercicio antes de crear la rutina");
            return;
        }
        
        r.setNombre(txf_nombre_rutina.getText().trim());
        r.setDescripcion(txa_descripcion.getText().trim());

        r.setEjercicioList(lst_ejercicios_añadir_BBDD);

        if (crud.InsertarRutina(r)) {
            JOptionPane.showMessageDialog(this, "Rutina creada correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "Fallo al crear la rutina");
        }


    }//GEN-LAST:event_btn_crear_rutinaActionPerformed

    private void btn_aniadir_ejercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aniadir_ejercicioActionPerformed
        // TODO add your handling code here:
        int index = cb_ejercicios.getSelectedIndex();
//      Así evitamos una excepción en la BBDD de ejercicios repetidos
        if (index != -1) {
            Ejercicio e = listaEjercicios.get(index);
            for (Ejercicio ejercicio : lst_ejercicios_añadir_BBDD) {
                if (ejercicio.getId() == e.getId()) {
                    JOptionPane.showMessageDialog(this, "Ejercicio ya añadido en la rutina seleccione otro  ");
                    return;
                }
            }
            dtm.addRow(new Object[]{e.getNombre(), e.getDescripcion(), e.getDescanso()});
            lst_ejercicios_añadir_BBDD.add(e);
        }

    }//GEN-LAST:event_btn_aniadir_ejercicioActionPerformed

    private void tb_ejercciciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_ejercciciosMouseClicked
        // TODO add your handling code here:
        int index = tb_ejerccicios.getSelectedRow();
        if (index != -1) {
            Ejercicio e = lst_ejercicios_añadir_BBDD.get(index);
            if (e.getImagen() != null) {
                lbl_imagen.setIcon(new ImageIcon(new ImageIcon(e.getImagen()).getImage().getScaledInstance(lbl_imagen.getWidth(), lbl_imagen.getHeight(), Image.SCALE_DEFAULT)));
            } else {
                lbl_imagen.setIcon(new ImageIcon());
            }
        }
    }//GEN-LAST:event_tb_ejercciciosMouseClicked

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        int index = tb_ejerccicios.getSelectedRow();
        if (index != -1) {
            dtm.removeRow(index);
            tb_ejerccicios.remove(index);
            lst_ejercicios_añadir_BBDD.remove(index);
            lbl_imagen.setIcon(new ImageIcon());
            tb_ejerccicios.updateUI();
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:        
        Crear_ejercicio crear_ej = new Crear_ejercicio(crud);
        crear_ej.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        cargar_cb();
        cb_ejercicios.updateUI();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear_rutina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear_rutina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear_rutina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear_rutina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear_rutina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aniadir_ejercicio;
    private javax.swing.JButton btn_crear_rutina;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JComboBox<String> cb_ejercicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_imagen;
    private javax.swing.JTable tb_ejerccicios;
    private javax.swing.JTextArea txa_descripcion;
    private javax.swing.JTextField txf_nombre_rutina;
    // End of variables declaration//GEN-END:variables

    private void cargar_cb() {
        try {
            listaEjercicios.clear();
            cb_ejercicios.removeAllItems();
            listaEjercicios = crud.ListarEjercicios();
            for (Ejercicio ejercicio : listaEjercicios) {
                cb_ejercicios.addItem(ejercicio.getNombre());
            }
        } catch (Exception e) {
        }

    }

}
