/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Vista.User.Crear_user;
import Vista.User.Ver_Usuarios;
import Vista.Rutina.Crear_rutina;
import Controlador.CRUD;
import Controlador.Utilidades;
import Vista.Ejercicio.Crear_ejercicio;
import Vista.Ejercicio.Ver_Ejercicios;
import Vista.Rutina.Consultar_Rutinas;

/**
 *
 * @author Alvaro Romo Villarreal
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private CRUD crud;
    private Utilidades util;

    /**
     * Creates new form Inicio_de_sesion
     */
    public VentanaPrincipal() {
        initComponents();
        util = new Utilidades();
        util.cambiarTema(this);
        this.setExtendedState(MAXIMIZED_BOTH);
        util.pintarImagen(lbl_wallpaper, "./recursos/img/BackgroundImage.jpg");
        crud = new CRUD("App_fitness_casa");

    }

//    public void paint(Graphics g) {
//        ImageIcon image = new ImageIcon("./recursos/img/BackgroundImage.jpg"); // load the image to a imageIcon
//        g.drawImage(image.getImage(), 0, 0, getWidth(), getHeight(), this);
//        setOpacity((float)0.01);
//        super.paint(g);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_wallpaper = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        mn_nuevoUsuario = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mn_consulta_usuarios = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mn_consultar_rutina = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jMenu4.setText("Añadir");

        mn_nuevoUsuario.setText("Nuevo Usuario");
        mn_nuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_nuevoUsuarioActionPerformed(evt);
            }
        });
        jMenu4.add(mn_nuevoUsuario);
        jMenu4.add(jSeparator4);

        jMenuItem3.setText("Crear Rutina");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);
        jMenu4.add(jSeparator5);

        jMenuItem4.setText("Crear Ejercicio");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem1.setText("Crear Tipo de Ejercicio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ver");

        mn_consulta_usuarios.setText("Usuarios");
        mn_consulta_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_consulta_usuariosActionPerformed(evt);
            }
        });
        jMenu5.add(mn_consulta_usuarios);
        jMenu5.add(jSeparator6);

        mn_consultar_rutina.setText("Ver Rutinas");
        mn_consultar_rutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_consultar_rutinaActionPerformed(evt);
            }
        });
        jMenu5.add(mn_consultar_rutina);
        jMenu5.add(jSeparator1);

        jMenuItem2.setText("Ejercicios / Tipo Ejercicios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_wallpaper, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_wallpaper, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_consulta_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_consulta_usuariosActionPerformed
        // TODO add your handling code here:
        Ver_Usuarios ver_users = new Ver_Usuarios(crud);
        ver_users.setVisible(true);

    }//GEN-LAST:event_mn_consulta_usuariosActionPerformed

    private void mn_nuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_nuevoUsuarioActionPerformed
        // TODO add your handling code here:
        Crear_user crear = new Crear_user(crud);
        crear.setVisible(true);
    }//GEN-LAST:event_mn_nuevoUsuarioActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Crear_rutina crearRutina = new Crear_rutina(crud);
        crearRutina.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Crear_ejercicio crear_ej = new Crear_ejercicio(crud);
        crear_ej.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mn_consultar_rutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_consultar_rutinaActionPerformed
        // TODO add your handling code here:
        Consultar_Rutinas cr = new Consultar_Rutinas(crud);
        cr.setVisible(true);

    }//GEN-LAST:event_mn_consultar_rutinaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        util.crearNuevoTipoEjercicio(crud);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Ver_Ejercicios ventana_vej = new Ver_Ejercicios(crud);
        ventana_vej.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        util.pintarImagen(lbl_wallpaper, "./recursos/img/BackgroundImage.jpg");        
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JLabel lbl_wallpaper;
    private javax.swing.JMenuItem mn_consulta_usuarios;
    private javax.swing.JMenuItem mn_consultar_rutina;
    private javax.swing.JMenuItem mn_nuevoUsuario;
    // End of variables declaration//GEN-END:variables
}
