/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Vista.User.Crear_user;
import Vista.User.Ver_Usuarios;
import Vista.Rutina.Crear_rutina;
import Controlador.CRUD;
import Vista.Ejercicio.Crear_ejercicio;
import Vista.Rutina.Consultar_Rutinas;


/**
 *
 * @author Alvaro Romo Villarreal
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private CRUD crud;
    /**
     * Creates new form Inicio_de_sesion
     */
    public VentanaPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        crud = new CRUD("App_fitness_casa");
    }

//    public void paint(Graphics g) {
//        ImageIcon image = new ImageIcon("./recursos/img/BackgroundImage.jpg"); // load the image to a imageIcon
//        g.drawImage(image.getImage(), 0, 0, getWidth(), getHeight(), this);
//        setOpacity((float)0.01);
//        super.paint(g);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_imgaen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mn_nuevoUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mn_consulta_usuarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mn_consultar_rutina = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Usuarios");

        mn_nuevoUsuario.setText("Nuevo Usuario");
        mn_nuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_nuevoUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(mn_nuevoUsuario);
        jMenu1.add(jSeparator1);

        mn_consulta_usuarios.setText("Ver Usuarios");
        mn_consulta_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_consulta_usuariosActionPerformed(evt);
            }
        });
        jMenu1.add(mn_consulta_usuarios);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Rutinas");

        mn_consultar_rutina.setText("Ver rutinas");
        mn_consultar_rutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_consultar_rutinaActionPerformed(evt);
            }
        });
        jMenu2.add(mn_consultar_rutina);
        jMenu2.add(jSeparator2);

        jMenuItem3.setText("Añadir Rutina");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ejercicios");

        jMenuItem4.setText("Añadir Ejercicio");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_imgaen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_imgaen, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_consulta_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_consulta_usuariosActionPerformed
        // TODO add your handling code here:
        Ver_Usuarios ver_users = new Ver_Usuarios(crud);
        ver_users.setVisible(true);
        
    }//GEN-LAST:event_mn_consulta_usuariosActionPerformed

    private void mn_nuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_nuevoUsuarioActionPerformed
        // TODO add your handling code here:
        Crear_user crear = new Crear_user(crud);
        crear.setVisible(true);
    }//GEN-LAST:event_mn_nuevoUsuarioActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Crear_rutina crearRutina = new Crear_rutina(crud);        
        crearRutina.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Crear_ejercicio crear_ej = new Crear_ejercicio(crud);        
        crear_ej.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mn_consultar_rutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_consultar_rutinaActionPerformed
        // TODO add your handling code here:
        Consultar_Rutinas cr = new Consultar_Rutinas(crud);
        cr.setVisible(true);
        
    }//GEN-LAST:event_mn_consultar_rutinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lbl_imgaen;
    private javax.swing.JMenuItem mn_consulta_usuarios;
    private javax.swing.JMenuItem mn_consultar_rutina;
    private javax.swing.JMenuItem mn_nuevoUsuario;
    // End of variables declaration//GEN-END:variables
}
