/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Ejercicio;

import Controlador.CRUD;
import Modelo.Ejercicio;
import Modelo.TipoEjercicio;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alvaro Romo Villarreal
 */
public class Ver_Ejercicios extends javax.swing.JFrame {

    private CRUD crud;
    private DefaultTableModel dtm_ejercicios;
    private List<Ejercicio> lst_ejercicios;
    private DefaultTableModel dtm_tipo_ejercicios;
    private List<TipoEjercicio> lst_tipo_ejercicios;

    /**
     * Creates new form Ver_Ejercicios
     */
    public Ver_Ejercicios() {
        initComponents();
    }

    public Ver_Ejercicios(CRUD crud) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.crud = crud;
        dtm_ejercicios = (DefaultTableModel) tb_ejercicios.getModel();
        dtm_tipo_ejercicios = (DefaultTableModel) tb_tipo_ejercicio.getModel();
        cargarTablaEjercicios();
        cargarTablaTipoEjercicios();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ejercicios = new javax.swing.JTable();
        btn_elimina_ejercicio = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_tipo_ejercicio = new javax.swing.JTable();
        btn_eliminar_tipo_ejercicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Ejercicios", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 24))); // NOI18N

        tb_ejercicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Descanso", "Tipo Ejercicio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_ejercicios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_ejercicios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_ejercicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_ejerciciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_ejercicios);

        btn_elimina_ejercicio.setText("Eliminar Ejercicio");
        btn_elimina_ejercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_elimina_ejercicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
                    .addComponent(btn_elimina_ejercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_elimina_ejercicio)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Tipos de Ejercicio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 24))); // NOI18N

        tb_tipo_ejercicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo Ejercicio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_tipo_ejercicio.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_tipo_ejercicio.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_tipo_ejercicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_tipo_ejercicioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_tipo_ejercicio);

        btn_eliminar_tipo_ejercicio.setText("Eliminar Tipo Ejericico");
        btn_eliminar_tipo_ejercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_tipo_ejercicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_eliminar_tipo_ejercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(btn_eliminar_tipo_ejercicio)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addGap(35, 35, 35)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_ejerciciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_ejerciciosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_ejerciciosMouseClicked

    private void btn_elimina_ejercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_elimina_ejercicioActionPerformed
        // TODO add your handling code here:
        int index = tb_ejercicios.getSelectedRow();
        if (index != -1) {
            int option = JOptionPane.showConfirmDialog(this, "Desea eliminar este ejercicio " + lst_ejercicios.get(index).getNombre());
            //      yes = 0, no = 1 , cancel = 2
            switch (option) {
                case 0:
                    crud.eliminarEjercicio(lst_ejercicios.get(index));
                    lst_ejercicios.remove(index);
                    cargarTablaEjercicios();
                    break;
                default:
                    break;
            }

        }
    }//GEN-LAST:event_btn_elimina_ejercicioActionPerformed

    private void btn_eliminar_tipo_ejercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_tipo_ejercicioActionPerformed
        // TODO add your handling code here:
        int index = tb_tipo_ejercicio.getSelectedRow();
        if (index != -1) {
            int option = JOptionPane.showConfirmDialog(this, "Desea eliminar este tipo de ejercicio " + lst_tipo_ejercicios.get(index).getTipoEjercicio());
            //      yes = 0, no = 1 , cancel = 2
            switch (option) {
                case 0:
                    crud.eliminarTipoDeEjercicio(lst_tipo_ejercicios.get(index));
                    cargarTablaTipoEjercicios();
                    break;
                default:
                    break;
            }

        }
    }//GEN-LAST:event_btn_eliminar_tipo_ejercicioActionPerformed

    private void tb_tipo_ejercicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_tipo_ejercicioMouseClicked
        // TODO add your handling code here:
        cargarTablaEjercicios();
    }//GEN-LAST:event_tb_tipo_ejercicioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ver_Ejercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ver_Ejercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ver_Ejercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ver_Ejercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ver_Ejercicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_elimina_ejercicio;
    private javax.swing.JButton btn_eliminar_tipo_ejercicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_ejercicios;
    private javax.swing.JTable tb_tipo_ejercicio;
    // End of variables declaration//GEN-END:variables

    private void cargarTablaEjercicios() {
        int index = tb_tipo_ejercicio.getSelectedRow();
        if (index != -1) {
            dtm_ejercicios.setRowCount(0);
            TipoEjercicio tipoEjercicio = lst_tipo_ejercicios.get(index);
            lst_ejercicios = tipoEjercicio.getEjercicioList();
            for (Ejercicio ejercicio : lst_ejercicios) {
                dtm_ejercicios.addRow(new Object[]{
                    ejercicio.getNombre().trim(),
                    ejercicio.getDescripcion().trim(),
                    ejercicio.getDescanso().trim(),
                    ejercicio.getIdTipoEjercicio().getTipoEjercicio()
                });
            }

        }

    }

    private void cargarTablaTipoEjercicios() {
        dtm_tipo_ejercicios.setRowCount(0);
        lst_tipo_ejercicios = crud.ListarTipoEjercicios();
        for (TipoEjercicio tipo_ej : lst_tipo_ejercicios) {
            dtm_tipo_ejercicios.addRow(new Object[]{
                tipo_ej.getTipoEjercicio()
            });
        }
        cargarTablaEjercicios();
    }
}
